<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: aisk
 * Date: Tue, 16 Aug 2022 20:32:10 +0000
 */

$conf['title'] = 'Wiki';
$conf['start'] = 'main';
$conf['tagline'] = 'Personal knowledge base.';
$conf['license'] = 'cc-zero';
$conf['breadcrumbs'] = 0;
$conf['dformat'] = '%Y-%m-%d %H:%M';
$conf['useacl'] = 1;
$conf['passcrypt'] = 'argon2id';
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['usewordblock'] = 0;
$conf['relnofollow'] = 0;
$conf['usedraft'] = 0;
$conf['subscribers'] = 1;
$conf['updatecheck'] = 0;
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['canonical'] = 1;
